[env:stm32_canbus]
platform = ststm32
board = genericSTM32F103CB
board_build.mcu = stm32f103cbt6
framework = arduino
upload_protocol = stlink

build_flags =
    -DHAL_CAN_MODULE_ENABLED
    ; Set HSE based on physical crystal
    -DHSE_VALUE=16000000U
    -Wall
    -Wextra
    -Werror
    ; TinyGPS++ emits an intentional fallthrough warning under this toolchain.
    -Wno-implicit-fallthrough
    -fno-exceptions

lib_deps =
    mikalhart/TinyGPSPlus @ ^1.1.0

lib_extra_dirs =
    ; Explicitly select only required libraries from the local monorepo
    ../../../av-libraries/
